wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
dataset:
  desc: null
  value: Cifar100
model_architecture:
  desc: null
  value: CIFAR100Classifier
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 2
num_rounds:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701602948.153142
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 30
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 30
      - 41
      - 50
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.10
      8:
      - 5
    visualize:
      Data Lable Histogram:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/bar/v0
          fieldSettings:
            label: label
            value: data_size
          stringSettings:
            title: Data Size Distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Data Lable Histogram_table
                fields: []
loss_function:
  desc: null
  value: CrossEntropyLoss()
